update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    ensure_git_status_clean()

    app_store_connect_api_key(
      key_id: "BR9339CXSN",
      issuer_id: "69a6de8c-ea4d-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./fastlane/AuthKey_BR9339CXSN.p8"
    )

    if not prompt(text: "Release notes up to date?", boolean: true)
      UI.user_error! "Update your release notes first :)"
    end

    version = increment_version_number(bump_type: "minor")
    user_version = prompt(text: "Version ('y' for default: #{version}):")
    if not user_version == 'y'
      version = increment_version_number(version_number: user_version)
    end

    build_number = increment_build_number(xcodeproj: "Paraquip.xcodeproj")

    build_app(scheme: "Paraquip", xcargs: "-allowProvisioningUpdates")

    capture_screenshots()

    commit_version_bump(message: "Version #{version} (#{build_number})")
    add_git_tag(sign: true)

    upload_to_app_store(
      overwrite_screenshots: true,
      copyright: "#{Time.now.year} Simon Seyer",
      precheck_include_in_app_purchases: false,
      submit_for_review: true,
      automatic_release: true,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end
end
