devices([
    "iPhone 14 Pro Max",
    # "iPhone 14 Pro", // Skipped until https://github.com/fastlane/fastlane/pull/20777 is merged 
    "iPhone 14 Plus",
    "iPhone 14",
    "iPhone SE (3rd generation)"
])

languages([
  "en-US",
  "de-DE",
])

scheme("ParaquipUITests")

clear_previous_screenshots(true)
override_status_bar(true)
stop_after_first_error(true)
localize_simulator(true)
