devices([
    "iPhone 12 Pro Max",
    "iPhone 12 Pro",
    "iPhone 8 Plus",
    "iPhone 8",
    "iPad Pro (12.9-inch) (6th generation)",
    "iPad Pro (11-inch) (4th generation)",
    "iPad mini (6th generation)"
])

languages([
  "en",
  "de",
])

scheme("ParaquipUITests")
launch_arguments(["isUITest"])

clear_previous_screenshots(true)
override_status_bar(true)
stop_after_first_error(true)
localize_simulator(true)
