devices([
    "iPhone 16 Plus",
    "iPad Air 13-inch (M3)",
])

languages([
  "en-US",
  "de-DE",
])

scheme("ParaquipUITests")
launch_arguments(["isUITest"])

clear_previous_screenshots(true)
override_status_bar(true)
stop_after_first_error(true)
localize_simulator(true)
